### ISSUE TITLE
filter size in multi_features_model

### ISSUE THREAD

**Issue by drsmith48** [PlasmaControl/bes-edgeml-models#10]
https://github.com/PlasmaControl/bes-edgeml-models/blob/b26f28b8655e7930e704df26d0bd747aa4bf063d/elm_classification/models/multi_features_model.py#L43

Spatial dimensions can be `8 // maxpool_size` to give flexibility for different maxpool sizes.

**Comment by LakshyaMalhotra** [comment]
Fixed. Added in the main branch.
