### ISSUE TITLE
feature modeel kernel size

### ISSUE THREAD

**Issue by drsmith48** [PlasmaControl/bes-edgeml-models#11]
https://github.com/PlasmaControl/bes-edgeml-models/blob/b26f28b8655e7930e704df26d0bd747aa4bf063d/elm_classification/models/feature_v3_model.py#L14

Is the conv kernel the full size of the input tensor for this feature model?  Maybe this is set in the model instantiation.

**Comment by LakshyaMalhotra** [comment]
This particular variant of the feature model actually used the receptive field of size smaller than the actual input tensor. We can specify the kernel size during the model instantiation but so far I just used the default size of the kernel `(3, 3, 3)`.
